# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AppleBridge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AppleBridge

# Your 'node_modules' directory is probably in the root of your project,
  		# but if not, adjust the `:path` accordingly
  	pod 'React', :path => '../../ReactNativeTemp/SampleApp/node_modules/react-native', :subspecs => [
    			'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTImage',
    'RCTWebSocket', # Needed for debugging
    # Add any other subspecs you want to use in your project
]

  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../../ReactNativeTemp/SampleApp/node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../../ReactNativeTemp/SampleApp/node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../../ReactNativeTemp/SampleApp/node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../../ReactNativeTemp/SampleApp/node_modules/react-native/third-party-podspecs/Folly.podspec'


  target 'AppleBridgeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AppleBridgeUITests' do
    # Pods for testing
  end

end
